#!/usr/bin/env bash
# =============================================================================
# ss-magic wrapper — graceful degradation when the binary is absent
# =============================================================================
#
# This file is committed to `.superset/magic.sh` in every consuming repo.
# When ss-magic is installed, it delegates to it via `exec` (propagating the
# real exit code).  When the binary is missing it prints an install hint and
# exits 0 so Superset's setup pipeline continues uninterrupted.
#
# Requirements: POSIX-compatible shell (bash, dash, sh).
# Generated by ss-magic — regenerated on every bootstrap/migration run.

set -u

# NO_COLOR-aware color setup (only emit ANSI when stderr is a TTY and
# NO_COLOR is unset, per https://no-color.org).
if [ -t 2 ] && [ -z "${NO_COLOR:-}" ]; then
    red='\033[1;31m'
    reset='\033[0m'
else
    red=''
    reset=''
fi

if command -v ss-magic >/dev/null 2>&1; then
    exec ss-magic "$@"
fi

# Binary not found — print install hint and exit 0 so the setup pipeline
# continues.  The tool is not required for repo setup to succeed; the user
# can install it later and re-run.
printf '%bss-magic is not installed.%b\n' "$red" "$reset" >&2
printf 'Install it from https://github.com/ViktorStiskala/superset-magic/releases\n' >&2
printf 'or run the installer:\n' >&2
printf '  curl -sSfL https://github.com/ViktorStiskala/superset-magic/releases/latest/download/ss-magic-installer.sh | sh\n' >&2
exit 0
